-- The schema is maintained by the ordered migrations in ../migrations/.
-- This file used to define an alternate schema with conflicting inventory and
-- QR-verification table names. It is intentionally documentation-only now.
-- Apply the migrations with the Supabase CLI; do not use this file to create tables.
